### PR TITLE
More basic shapes

### PR DESCRIPTION
**Pull request by LegenDAirie**
So far I have only added triangles as additional shapes. Before I start adding more shapes I wanted to make sure the structural changes won't interfere with anything.

In the issue I opened you mentioned that I should make sure not to expose the BasicShape constructors. I ended up putting the BasicShape type in the Render file where it's used exclusively so I didn't even need to expose BasicShape.

Let me know if I am on the right track

### CODE REVIEW

**Comment by Zinggi** [comment]
Thanks for doing this!
Yup, this looks good to me, you seem to be on the right track.

However, if we add more shapes this way, the API might become too cluttered. So I think it would be better if you wouldn't expose a separate render function for each shape, but only a single one that takes as a first argument the shape type.

So instead of having `rectangle, triangle, etc..` it would probably be easier to only have `shape`, where `shape : BasicShape -> { ... } -> Renderable`.
A user can then draw a rectangle using `shape rectangle {...}`.
So only expose `shape(Z/WithOptions)`, `BasicShape` and it's constructors like `rectangle = Rectangle` etc.

**Comment by LegenDAirie** [comment]
Yeah np! I would rather spend time giving back instead of spending way too much time to figure out and implement WebGL from scratch.

My first thought when making the triangle function was that It would indeed get too cluttered. Using shape : BasicShape -> { ... } -> Renderable sounds like that best path to take to me as well but won't people need access to Rectangle, Triangle to pass them in? If so that would require a major version change for every new shape right? Maybe I am misunderstanding what you mean by exposing constructors, I thought the rectangle, rectangleZ and rectangleWithOptions were kind of constructor functions. Are you talking about something like this?

```
module Game.TwoD.Render exposing (rectangle, triangle)

type BasicShape
    = Rectangle
    | Triangle

rectangle: BasicShape
rectangle = Rectangle

triangle: BasicShape
triangle = Triangle
```
If that is what you mean how would exposing rectangle instead of Rectangle help?

Out of curiosity do we have to expose BasicShape?

**Comment by Zinggi** [comment]
> Are you talking about something like this? `...`

Yes, that's exactly what I meant. This is also what e.g. http://package.elm-lang.org/packages/elm-community/webgl/2.0.3/WebGL-Settings#FaceMode does. It's a common pattern in elm.

The difference to exposing an alias for the constructors instead of the actual constructor (`triangle` vs. `Triangle`) is that people can't write code that pattern matches on a `BasicShape`.

If you would expose the actual constructors, adding a new case would break code that pattern matches on a `BasicShape`, because it's suddenly no longer exhaustive, hence it would be a major version bump.

However if you only expose the aliases, adding new cases cannot possibly break anyone's code, so it would only be a minor version bump.

> Out of curiosity do we have to expose BasicShape?

Definitely, otherwise people wouldn't be able to write type declarations.

**Comment by LegenDAirie** [comment]
Ok, I made the relevant changes. If they are good I will start adding more shapes.
Thanks again for the detailed explanation

**Comment by Zinggi** [comment]
Thanks!
Yes, this looks good.
You can go ahead as you like.
Tell me when you think it's ready, then I'll find some time and merge your changes in.

**Comment by LegenDAirie** [comment]
I encountered a weird rendering bug having to do with the order and overlapping shapes. It looks like when something is rendered through the blender in "renderTransparent" its ordering behaves very different than if it was just rendered with "WebGL.entity".  I played with every blender combination I could but had no luck.

Because words can not do this bug any justice here are some pictures.
The red circle is put through "renderTransparent" and everything else is just using "WebGL.entity".

### Example One
The order they are rendered
screen shot 2017-04-01 at 10 05 29 pm

The result
screen shot 2017-04-01 at 10 04 28 pm

### Example Two
The order they are rendered
screen shot 2017-04-01 at 10 05 59 pm

The result
screen shot 2017-04-01 at 10 05 43 pm
screen shot 2017-04-01 at 10 05 51 pm


A simple solution I found was just to run everything through "renderTransparent". However, It seems to flip the render order. Anyone updating to the new version of this library would see all of their rectangles overlap in the opposite order but anyone using mostly sprites would not see an ordering difference. Since shapes are just for prototyping I say let's do it.

**Comment by Zinggi** [comment]
It's not a bug, it's a feature :grimacing: 
WebGL does exactly what it was instructed to do. This is expected behavior when mixing transparent rendering with non transparent. It turns out transparency is a complicated subject in graphics programming.

The solutions are usually to sort all entities and render them in some [ideal order](https://www.khronos.org/opengl/wiki/Transparency_Sorting).

So making all prototype shapes transparent seems to be an ok solution that won't cause us any headaches.

**Comment by LegenDAirie** [comment]
That was a very interesting read. I do remember hearing about this, I have just never seen it in action. This solution shouldn't cause us any headaches because we are working in just 2D and not 3D, is that right?

**Comment by LegenDAirie** [comment]
So far we now have rectangles, triangles, circles, and rings. The rest would be great nice to haves but implementing them will be quite an ordeal. Just the circle and ring were very challenging.

## The last hold up

* When something is being rendered It looks like the position refers to the bottom left corner. That works fine for rectangles but not for circles. 
My first thought is to make the center of the shapes be the position by changing the unitShape to have (0, 0) at the center. However, the position being at the center of a right triangle might feel awkward.

#### Potential solutions
* Change the position of rectangles, circles, and rings to their center and keep triangles position at the bottom left.

* Make all triangles be equilateral triangles instead of right triangles so all shapes can have their position refer to their center.

any thoughts?

**Comment by Zinggi** [comment]
Yap, I think that's enough shapes for now. Thanks a lot!

When I find some time (hopefully this weekend), I'll merge your changes in.

Don't worry about the positioning, it's something I wanted to change anyway.
Currently the pivot only affects the center of rotation and scale, but not the position.
I think it would be better if it would also affect the position.
I'll do that change together with your changes, as it's also a breaking change.

With that change, a user can decide where position should refer to. Bottom rigth? default. Center? `(0.5, 0.5)`. Bottom center? `(0.5, 0)`, etc.

**Comment by LegenDAirie** [comment]
You are very welcome!

It's really nice to help contribute to something that I use regularly.

I am also interested in changing the way animated sprites receive time. It would be nice if sprites could act on their own time so that every animated sprite isn't on a global frame number. Should I open up another issue? Also, should we try and take care of all breaking changes we can before you update?

**Comment by Zinggi** [comment]
This is now merged into master, thanks!

I also did some refactoring while merging, as I was already working on that before you started implementing the new features. So you might no longer recognise your code, but the features are in :smile: 

> I am also interested in changing the way animated sprites receive time. It would be nice if sprites could act on their own time so that every animated sprite isn't on a global frame number. Should I open up another issue?

Yes, please open another issue. If implementing that also is a breaking change, then I'll wait with publishing 3.0.0

**Pull request merged**
